
[build]
rustflags = [
    "-Ctarget-cpu=native",
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
    "-Zunstable-options",
    # "-Cpanic=immediate-abort",
    "-Clink-arg=-nostartfiles",
]

[unstable]
build-std = ["core", "compiler_builtins"]
